import { describe, it } from "node:test";
import assert from "node:assert";
import { parse as parseYaml } from "yaml";
import { serializeHayagriva } from "../domain/HayagrivaSerializer.js";
import type { BibEntry } from "../domain/BibEntry.js";

function asMap(raw: unknown): Record<string, unknown> {
  assert.ok(raw && typeof raw === "object" && !Array.isArray(raw));
  return raw as Record<string, unknown>;
}

describe("serializeHayagriva", () => {
  it("emits a YAML map keyed by citation key", () => {
    const entries: BibEntry[] = [
      { key: "smith2024", type: "article", fields: { title: "Hello", year: "2024" } },
      { key: "doe2023", type: "book", fields: { title: "World", year: "2023" } },
    ];
    const out = serializeHayagriva(entries);
    const parsed = asMap(parseYaml(out));
    assert.ok("smith2024" in parsed);
    assert.ok("doe2023" in parsed);
  });

  it("prepends a generator header comment", () => {
    const out = serializeHayagriva([
      { key: "k", type: "misc", fields: { title: "t" } },
    ]);
    assert.match(out, /^# Generated by TLU Scholar Editor — Hayagriva YAML format/);
  });

  it("maps an article with journal/volume/issue/pages into parent + page-range", () => {
    const entry: BibEntry = {
      key: "clark1988",
      type: "article",
      fields: {
        title: "Error-correction coding",
        author: "Clark, George C. and Cain, Joseph B.",
        year: "1988",
        journal: "IEEE Transactions",
        volume: "36",
        number: "2",
        pages: "145-159",
        doi: "10.1109/26.2755",
      },
    };
    const out = serializeHayagriva([entry]);
    const parsed = asMap(parseYaml(out));
    const e = asMap(parsed.clark1988);
    assert.strictEqual(e.type, "article");
    assert.strictEqual(e.title, "Error-correction coding");
    assert.deepStrictEqual(e.author, ["Clark, George C.", "Cain, Joseph B."]);
    assert.strictEqual(e.date, 1988);
    assert.strictEqual((e["page-range"] as string), "145-159");
    const serial = asMap(e["serial-number"]);
    assert.strictEqual(serial.doi, "10.1109/26.2755");
    const parent = asMap(e.parent);
    assert.strictEqual(parent.type, "periodical");
    assert.strictEqual(parent.title, "IEEE Transactions");
    assert.strictEqual(parent.volume, 36);
    assert.strictEqual(parent.issue, 2);
  });

  it("maps a book with publisher/address/edition/isbn", () => {
    const entry: BibEntry = {
      key: "knuth1984",
      type: "book",
      fields: {
        title: "The Art of Computer Programming",
        author: "Knuth, Donald E.",
        year: "1984",
        publisher: "Addison-Wesley",
        address: "Reading, MA",
        edition: "3",
        isbn: "0-201-03801-6",
      },
    };
    const out = serializeHayagriva([entry]);
    const parsed = asMap(parseYaml(out));
    const e = asMap(parsed.knuth1984);
    assert.strictEqual(e.type, "book");
    assert.strictEqual(e.publisher, "Addison-Wesley");
    assert.strictEqual(e.location, "Reading, MA");
    assert.strictEqual(e.edition, "3");
    assert.strictEqual(asMap(e["serial-number"]).isbn, "0-201-03801-6");
  });

  it("maps inproceedings into article + parent type=proceedings", () => {
    const entry: BibEntry = {
      key: "lecun2015",
      type: "inproceedings",
      fields: {
        title: "Deep Learning",
        author: "LeCun, Yann and Bengio, Yoshua",
        year: "2015",
        booktitle: "Proceedings of ICML",
        pages: "1200-1220",
      },
    };
    const out = serializeHayagriva([entry]);
    const parsed = asMap(parseYaml(out));
    const e = asMap(parsed.lecun2015);
    assert.strictEqual(e.type, "article");
    assert.strictEqual(asMap(e.parent).type, "proceedings");
    assert.strictEqual(asMap(e.parent).title, "Proceedings of ICML");
  });

  it("maps phdthesis to type=thesis", () => {
    const entry: BibEntry = {
      key: "reynolds2020",
      type: "phdthesis",
      fields: {
        title: "Advanced Bibliography",
        author: "Reynolds, Claire",
        year: "2020",
        publisher: "MIT",
      },
    };
    const out = serializeHayagriva([entry]);
    const parsed = asMap(parseYaml(out));
    assert.strictEqual(asMap(parsed.reynolds2020).type, "thesis");
  });

  it("emits date as YYYY-MM when month is recognisable", () => {
    const entry: BibEntry = {
      key: "k",
      type: "misc",
      fields: { title: "t", year: "2024", month: "march" },
    };
    const out = serializeHayagriva([entry]);
    const parsed = asMap(parseYaml(out));
    assert.strictEqual(asMap(parsed.k).date, "2024-03");
  });

  it("drops month when unrecognised, keeps year", () => {
    const entry: BibEntry = {
      key: "k",
      type: "misc",
      fields: { title: "t", year: "2024", month: "spring" },
    };
    const out = serializeHayagriva([entry]);
    const parsed = asMap(parseYaml(out));
    assert.strictEqual(asMap(parsed.k).date, 2024);
  });
});
