
import { Document, Pair, YAMLMap, YAMLSeq } from "yaml";
import type { BibEntry, BibEntryType } from "./BibEntry.js";

const HEADER_COMMENT =
  " Generated by TLU Scholar Editor — Hayagriva YAML format";

export function serializeHayagriva(entries: BibEntry[]): string {
  const doc = new Document();
  doc.commentBefore = HEADER_COMMENT;
  const root = new YAMLMap();
  doc.contents = root;

  for (const entry of entries) {
    root.add(new Pair(entry.key, buildEntryNode(entry)));
  }

  return doc.toString({
    lineWidth: 0,
    defaultStringType: "QUOTE_DOUBLE",
    defaultKeyType: "PLAIN",
    blockQuote: "literal",
  });
}

function buildEntryNode(entry: BibEntry): YAMLMap {
  const node = new YAMLMap();
  const f = entry.fields;

  node.add(new Pair("type", mapType(entry.type)));

  if (f.title) node.add(new Pair("title", f.title));

  const authorList = splitAndList(f.author);
  if (authorList) node.add(new Pair("author", authorList));
  const editorList = splitAndList(f.editor);
  if (editorList) node.add(new Pair("editor", editorList));

  if (f.year) {
    const d = buildDate(f.year, f.month);
    node.add(new Pair("date", d));
  }

  const serial = buildSerial(f.doi, f.isbn, f.issn);
  if (serial) node.add(new Pair("serial-number", serial));

  if (f.pages) node.add(new Pair("page-range", f.pages));

  const parent = buildParent(entry);
  if (parent) node.add(new Pair("parent", parent));

  if (f.publisher) node.add(new Pair("publisher", f.publisher));
  if (f.address) node.add(new Pair("location", f.address));
  if (f.edition) node.add(new Pair("edition", f.edition));

  if (f.url) node.add(new Pair("url", f.url));

  if (f.abstract) node.add(new Pair("abstract", f.abstract));
  if (f.note) node.add(new Pair("note", f.note));
  if (f.keywords) node.add(new Pair("keywords", f.keywords));
  if (f.series) node.add(new Pair("series", f.series));

  return node;
}

function mapType(type: BibEntryType): string {
  switch (type) {
    case "article":
      return "article";
    case "book":
      return "book";
    case "incollection":
      return "chapter";
    case "inproceedings":
      return "article";
    case "phdthesis":
    case "mastersthesis":
      return "thesis";
    case "techreport":
      return "report";
    case "misc":
      return "misc";
    default:
      return "misc";
  }
}

function splitAndList(value: string | undefined): YAMLSeq | null {
  if (!value) return null;
  const parts = value
    .split(/\s+and\s+/)
    .map((s) => s.trim())
    .filter(Boolean);
  if (parts.length === 0) return null;
  const seq = new YAMLSeq();
  for (const part of parts) seq.add(part);
  return seq;
}

function buildDate(year: string, month?: string): number | string {
  const yearNum = /^\d{1,4}$/.test(year) ? parseInt(year, 10) : null;
  if (!month) return yearNum ?? year;
  const m = monthToNumber(month);
  if (!m) return yearNum ?? year;
  return `${year}-${m.padStart(2, "0")}`;
}

function monthToNumber(m: string): string | null {
  const trimmed = m.trim().toLowerCase();
  if (/^\d{1,2}$/.test(trimmed)) {
    const n = parseInt(trimmed, 10);
    if (n >= 1 && n <= 12) return String(n);
  }
  const months: Record<string, string> = {
    jan: "1", january: "1",
    feb: "2", february: "2",
    mar: "3", march: "3",
    apr: "4", april: "4",
    may: "5",
    jun: "6", june: "6",
    jul: "7", july: "7",
    aug: "8", august: "8",
    sep: "9", september: "9",
    oct: "10", october: "10",
    nov: "11", november: "11",
    dec: "12", december: "12",
  };
  return months[trimmed] ?? null;
}

function buildSerial(
  doi: string | undefined,
  isbn: string | undefined,
  issn: string | undefined,
): YAMLMap | null {
  if (!doi && !isbn && !issn) return null;
  const m = new YAMLMap();
  if (doi) m.add(new Pair("doi", doi));
  if (isbn) m.add(new Pair("isbn", isbn));
  if (issn) m.add(new Pair("issn", issn));
  return m;
}

function buildParent(entry: BibEntry): YAMLMap | null {
  const f = entry.fields;
  const hasJournalLike = !!(f.journal || f.booktitle);
  if (!hasJournalLike && !f.volume && !f.number) return null;

  const parent = new YAMLMap();
  if (entry.type === "article" && f.journal) {
    parent.add(new Pair("type", "periodical"));
    parent.add(new Pair("title", f.journal));
  } else if (entry.type === "inproceedings" && f.booktitle) {
    parent.add(new Pair("type", "proceedings"));
    parent.add(new Pair("title", f.booktitle));
  } else if (entry.type === "incollection" && f.booktitle) {
    parent.add(new Pair("type", "anthology"));
    parent.add(new Pair("title", f.booktitle));
  } else if (f.journal) {
    parent.add(new Pair("type", "periodical"));
    parent.add(new Pair("title", f.journal));
  } else if (f.booktitle) {
    parent.add(new Pair("title", f.booktitle));
  }

  if (f.volume) parent.add(new Pair("volume", numericOrString(f.volume)));
  if (f.number) parent.add(new Pair("issue", numericOrString(f.number)));

  return parent.items.length > 0 ? parent : null;
}

function numericOrString(value: string): number | string {
  if (/^\d+$/.test(value)) return parseInt(value, 10);
  return value;
}
