/**
 * Hayagriva YAML Serializer
 *
 * Converts BibEntry domain objects to Hayagriva YAML format used by Typst
 * native `#bibliography("…")` when the file ends with `.yml`/`.yaml`.
 *
 * Schema is locked to hayagriva@0.9.1 — the same version vendored inside
 * tinymist (see references/tinymist/Cargo.toml) and Typst itself. The
 * mapping below was derived from
 *   - references/tinymist/crates/tinymist-query/src/analysis/bib.rs
 *   - https://github.com/typst/hayagriva file-format docs
 *
 * Round-trip note: BibTeX has flat string fields and Hayagriva has nested
 * `parent` + `serial-number` + author lists. We preserve the data on a
 * lossless basis (the reverse parser at HayagrivaParser.ts reconstructs the
 * BibEntry shape), but field ORDER in the YAML output is fixed for
 * readability.
 */

import { Document, Pair, YAMLMap, YAMLSeq } from "yaml";
import type { BibEntry, BibEntryType } from "./BibEntry.js";

const HEADER_COMMENT =
  " Generated by TLU Scholar Editor — Hayagriva YAML format";

/**
 * Serialize a list of bibliography entries to a Hayagriva YAML document.
 *
 * @param entries - Bibliography entries
 * @returns YAML string with stable field ordering and double-quoted values
 */
export function serializeHayagriva(entries: BibEntry[]): string {
  const doc = new Document();
  doc.commentBefore = HEADER_COMMENT;
  const root = new YAMLMap();
  doc.contents = root;

  for (const entry of entries) {
    root.add(new Pair(entry.key, buildEntryNode(entry)));
  }

  return doc.toString({
    lineWidth: 0,
    defaultStringType: "QUOTE_DOUBLE",
    defaultKeyType: "PLAIN",
    blockQuote: "literal",
  });
}

function buildEntryNode(entry: BibEntry): YAMLMap {
  const node = new YAMLMap();
  const f = entry.fields;

  // 1. type (mandatory in Hayagriva)
  node.add(new Pair("type", mapType(entry.type)));

  // 2. title
  if (f.title) node.add(new Pair("title", f.title));

  // 3. author / editor — list form
  const authorList = splitAndList(f.author);
  if (authorList) node.add(new Pair("author", authorList));
  const editorList = splitAndList(f.editor);
  if (editorList) node.add(new Pair("editor", editorList));

  // 4. date — combine month + year when both present (number for plain year)
  if (f.year) {
    const d = buildDate(f.year, f.month);
    node.add(new Pair("date", d));
  }

  // 5. serial-number (doi / isbn / issn)
  const serial = buildSerial(f.doi, f.isbn, f.issn);
  if (serial) node.add(new Pair("serial-number", serial));

  // 6. page-range
  if (f.pages) node.add(new Pair("page-range", f.pages));

  // 7. parent (journal / booktitle wrap)
  const parent = buildParent(entry);
  if (parent) node.add(new Pair("parent", parent));

  // 8. publisher / location / edition
  if (f.publisher) node.add(new Pair("publisher", f.publisher));
  if (f.address) node.add(new Pair("location", f.address));
  if (f.edition) node.add(new Pair("edition", f.edition));

  // 9. url
  if (f.url) node.add(new Pair("url", f.url));

  // 10. abstract / note / keywords / series
  if (f.abstract) node.add(new Pair("abstract", f.abstract));
  if (f.note) node.add(new Pair("note", f.note));
  if (f.keywords) node.add(new Pair("keywords", f.keywords));
  if (f.series) node.add(new Pair("series", f.series));

  return node;
}

/**
 * Map BibTeX entry type to Hayagriva `type` value.
 * Hayagriva's vocabulary is open-ended; we use the closest canonical values
 * that match `hayagriva::EntryType` (see hayagriva crate docs).
 */
function mapType(type: BibEntryType): string {
  switch (type) {
    case "article":
      return "article";
    case "book":
      return "book";
    case "incollection":
      return "chapter";
    case "inproceedings":
      return "article"; // distinguished from journal article by parent.type
    case "phdthesis":
    case "mastersthesis":
      return "thesis";
    case "techreport":
      return "report";
    case "misc":
      return "misc";
    default:
      // Defensive — keep type info if a new BibEntryType is added later.
      return "misc";
  }
}

function splitAndList(value: string | undefined): YAMLSeq | null {
  if (!value) return null;
  const parts = value
    .split(/\s+and\s+/)
    .map((s) => s.trim())
    .filter(Boolean);
  if (parts.length === 0) return null;
  const seq = new YAMLSeq();
  for (const part of parts) seq.add(part);
  return seq;
}

function buildDate(year: string, month?: string): number | string {
  // Hayagriva date supports ISO 8601 (YYYY, YYYY-MM, YYYY-MM-DD).
  // Convert month name → number when possible. When only year is present we
  // emit it as a YAML number (idiomatic Hayagriva), otherwise as a string.
  const yearNum = /^\d{1,4}$/.test(year) ? parseInt(year, 10) : null;
  if (!month) return yearNum ?? year;
  const m = monthToNumber(month);
  if (!m) return yearNum ?? year;
  return `${year}-${m.padStart(2, "0")}`;
}

function monthToNumber(m: string): string | null {
  const trimmed = m.trim().toLowerCase();
  if (/^\d{1,2}$/.test(trimmed)) {
    const n = parseInt(trimmed, 10);
    if (n >= 1 && n <= 12) return String(n);
  }
  const months: Record<string, string> = {
    jan: "1", january: "1",
    feb: "2", february: "2",
    mar: "3", march: "3",
    apr: "4", april: "4",
    may: "5",
    jun: "6", june: "6",
    jul: "7", july: "7",
    aug: "8", august: "8",
    sep: "9", september: "9",
    oct: "10", october: "10",
    nov: "11", november: "11",
    dec: "12", december: "12",
  };
  return months[trimmed] ?? null;
}

function buildSerial(
  doi: string | undefined,
  isbn: string | undefined,
  issn: string | undefined,
): YAMLMap | null {
  if (!doi && !isbn && !issn) return null;
  const m = new YAMLMap();
  if (doi) m.add(new Pair("doi", doi));
  if (isbn) m.add(new Pair("isbn", isbn));
  if (issn) m.add(new Pair("issn", issn));
  return m;
}

function buildParent(entry: BibEntry): YAMLMap | null {
  const f = entry.fields;
  const hasJournalLike = !!(f.journal || f.booktitle);
  if (!hasJournalLike && !f.volume && !f.number) return null;

  const parent = new YAMLMap();
  if (entry.type === "article" && f.journal) {
    parent.add(new Pair("type", "periodical"));
    parent.add(new Pair("title", f.journal));
  } else if (entry.type === "inproceedings" && f.booktitle) {
    parent.add(new Pair("type", "proceedings"));
    parent.add(new Pair("title", f.booktitle));
  } else if (entry.type === "incollection" && f.booktitle) {
    parent.add(new Pair("type", "anthology"));
    parent.add(new Pair("title", f.booktitle));
  } else if (f.journal) {
    parent.add(new Pair("type", "periodical"));
    parent.add(new Pair("title", f.journal));
  } else if (f.booktitle) {
    parent.add(new Pair("title", f.booktitle));
  }

  if (f.volume) parent.add(new Pair("volume", numericOrString(f.volume)));
  if (f.number) parent.add(new Pair("issue", numericOrString(f.number)));

  return parent.items.length > 0 ? parent : null;
}

function numericOrString(value: string): number | string {
  // Hayagriva accepts both `volume: 6` and `volume: "6A"`; prefer number when
  // the field is pure digits so output looks idiomatic.
  if (/^\d+$/.test(value)) return parseInt(value, 10);
  return value;
}
